/**
 * Secrets, which `wrangler types` cannot see.
 *
 * `worker-configuration.d.ts` is generated from `wrangler.jsonc`, so it knows
 * every binding and every plain var and nothing at all about anything set with
 * `wrangler secret put`. Declaring them there is not an option either — the
 * file is regenerated by `pnpm typecheck` and is not in the repo. So they are
 * declared here, merged into the same global `Env` the generated file declares.
 *
 * Optional, and that is the type doing real work rather than being cautious: an
 * environment with no secret set is the normal state of a local `pnpm dev`, and
 * a route that reads one has to say what it does about that.
 */
interface Env {
  /**
   * Proof that a caller is allowed to destroy the world — see
   * `app/routes/reset.ts`. Set with `wrangler secret put RESET_SECRET`, and for
   * local work in `.dev.vars`. Unset means the route is not there at all.
   */
  RESET_SECRET?: string;
}
